#!/usr/bin/env -S deno run --allow-run --allow-read --allow-env

// (c) 2024, 384 (tm) Inc

// convenience script to run various os384 cli tools as subcommands

const UTILS_PATH = new URL("./utils.lib.ts", import.meta.url).pathname
const {
    VERSION
} = await import(UTILS_PATH);

const subcommands = {
    'authorize-channel': '384.authorize.channel.ts',
    'create-channel': '384.create.channel.ts',
    'create-sb384': '384.create.sb384.ts',
    'refresh-token': '384.refresh.token.ts',
    'stream-channel': '384.stream.channel.ts',
};

const args = Deno.args;
const subcommand = args[0];

if (subcommand in subcommands) {
    const scriptPath = subcommands[subcommand];
    const process = Deno.run({
        cmd: [scriptPath, ...args.slice(1)],
        stdout: 'inherit',
        stderr: 'inherit',
    });
    const { code } = await process.status();
} else if(subcommand === 'help' || subcommand === '--help' || subcommand === '-h') {
    console.log('usage: 384 <subcommand> [args]\n')
    console.log('Available subcommands:')
    for (const key in subcommands) {
        console.log(`- ${key}`);
    }
} else if (subcommand === 'version' || subcommand === '--version' || subcommand === '-v') {
    console.log(VERSION)
} else {
    console.log('usage: 384 <subcommand> [args]\n')
}